version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: innerpeace
    ports:
      - "8080:8080"
    environment:
      - LAAS_API_KEY
      - LAAS_PROJECT_ID

