name: Innerpeace CI/CD

on:
  push:
    branches: [ main,develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: sangwonee/innerpeace:latest
        file: server/Dockerfile
        context: server

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull sangwonee/innerpeace:latest
          docker stop innerpeace || true
          docker rm innerpeace || true
          docker run -d --name innerpeace -p 8080:8080 sangwonee/innerpeace:latest
